root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 750
exclude_regex = ["_test.go" "_templ.go"]
include_ext = ["go", "tpl", "tmpl", "html", "templ", "css"]
pre_cmd = ["templ generate" "tailwindcss -i templates/style.css -o static/style.css -m"]

exclude_dir = ["tmp" "testdata" "vendor" "node_modules" "static"]

