root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 750
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go" "_templ.go"]
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
pre_cmd = ["templ generate"]

